language: php
sudo: false

php:
  - 7
  - 7.1
  - hhvm


before_script:
  - composer self-update
  - composer update


script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover